name: 🚀 Run Tests and Publish Allure Report

on:
  push:
    branches: [ jenkins-start, main ]
  pull_request:
    branches: [ jenkins-start, main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: 🔧 Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ⚡ Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: 🧪 Run tests via Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=testsSuites/testing.xml

      - name: 💾 Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results

      - name: 📊 Generate Allure HTML report
        if: always()
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip -q allure.zip -d allure
          ./allure/bin/allure generate target/allure-results -o target/allure-report --clean

      - name: 🚀 Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
          publish_branch: gh-pages
