name: Run UI and API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/example  # Не кэшируем собственные артефакты
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Chrome (for UI tests)
        uses: browser-actions/setup-chrome@v1

      - name: Verify Chrome version
        run: google-chrome --version

      - name: Run tests with Maven
        run: mvn clean test

      # Если используешь Allure:
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      # Можно добавить генерацию и публикацию отчёта, если используешь GitHub Pages или Allure S