name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Create .env file
        run: |
          cat <<EOF > .env
          API_TOKEN=7e321f4a663e7a4634c6a49921e3bea6e2438bc111ab278fbc68ea649fad5e9d
          BASE_URI=https://api.qase.io/v1/project
          BASE_URL=https://app.qase.io
          BROWSER=chrome
          EMAIL=martyniukvaleriya@gmail.com
          PASSWORD=91=Q7)3!O?gu
          EOF

      - name: Run tests via Maven
        run: mvn clean test

      - name: Upload Allure raw results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure HTML report
        run: |
          mkdir -p allure-report
          npx allure-commandline generate allure-results --clean -o target/allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
